# write_*_report() functions -> docs/*.md. Numbers come only from the tibbles
# already validated by 09_analyse.R / 10_analyse_comparators.R; the source
# URLs come only from config/config.yaml, never typed inline here.

`%||%` <- function(x, y) if (is.null(x)) y else x

#' Goal-type and comparator coverage, with the denominator always shown next
#' to the percentage -- "unknown" reported alongside classified types, never
#' folded in or dropped.
#'
#' @param goal_type_breakdown Output of `goal_type_breakdown()`.
#' @param contemporary_overview Output of `contemporary_overview()`.
#' @param path Output file path.
#' @param comparator_coverage_gaps Character vector naming each historical
#'   comparator match report the Internet Archive had no capture of at all
#'   (Phase 7's `comparator_context_breakdowns` target) -- declared by name,
#'   not folded into a percentage.
#' @return The `path` written to, invisibly usable for chaining into `_targets.R`.
#' @export
write_coverage_report <- function(goal_type_breakdown, contemporary_overview, path,
                                   comparator_coverage_gaps = character(0)) {
  n_total <- goal_type_breakdown$n_total[[1]]

  lines <- c(
    "# Coverage report",
    "",
    glue("Generated by `R/12_reports.R`. n = {n_total} goals total."),
    "",
    "## Goal type",
    kable(
      goal_type_breakdown |>
        transmute(Type = goal_type_group, Goals = n, Share = percent(share, accuracy = 1)),
      format = "markdown"
    )
  )

  lines <- c(
    lines, "",
    "## Contemporary comparator coverage",
    glue("- Seasons covered: **{contemporary_overview$seasons}**"),
    glue("- Seasons in that season's top 10: **{contemporary_overview$times_in_top10}**"),
    glue("- Seasons led the league: **{contemporary_overview$times_led}**")
  )

  lines <- c(
    lines, "",
    "## Historical comparator match reports with no Wayback capture",
    glue("{length(comparator_coverage_gaps)} match report(s) the Internet Archive had no snapshot",
         " of at all, across the 9 non-Shearer comparators (Phase 7). Excluded from that",
         " player's context-breakdown denominator, not imputed.")
  )
  if (length(comparator_coverage_gaps) > 0) {
    lines <- c(lines, "", paste0("- ", sort(comparator_coverage_gaps)))
  }

  writeLines(lines, path)
  path
}

#' Column-by-column description of every processed table, generated from the
#' actual columns present rather than a hand-maintained list that can drift.
#'
#' @param tables A named list of tibbles, one entry per processed table.
#' @param path Output file path.
#' @return The `path` written to, invisibly usable for chaining into `_targets.R`.
#' @export
write_data_dictionary <- function(tables, path) {
  lines <- c("# Data dictionary", "", "Generated by `R/12_reports.R` from the processed tables' own columns.")
  for (table_name in names(tables)) {
    tbl <- tables[[table_name]]
    cols <- tibble(Column = names(tbl), Type = map_chr(tbl, ~ class(.x)[[1]]))
    lines <- c(lines, "", glue("## `{table_name}`"), kable(cols, format = "markdown"))
  }
  writeLines(lines, path)
  path
}

#' Sources actually used (URLs from cfg, never hardcoded) and sources
#' considered and rejected, with why -- see the project plan for the full
#' investigation (FBref/Cloudflare, fbrapi.com down, worldfootballR event
#' coverage starting 2018).
#'
#' @param cfg Parsed config list (from `load_config()` / config/config.yaml).
#' @param path Output file path.
#' @return The `path` written to, invisibly usable for chaining into `_targets.R`.
#' @export
write_methodology_report <- function(cfg, path) {
  # Only sources with a fetchable endpoint (url/base_url/api) are listed here.
  # wikipedia_all_time_scorers has just a `page` field -- it's fetched through
  # the same wikipedia_season_results api endpoint, already listed below.
  urls <- map_chr(cfg$sources, ~ .x$url %||% .x$base_url %||% .x$api %||% NA_character_)
  sources_used <- tibble(Source = names(urls), URL = urls) |> filter(!is.na(URL))

  lines <- c(
    "# Methodology",
    "",
    "Generated by `R/12_reports.R`. Every number in this project traces to a",
    "cached fetch in `data/raw/source_manifest.csv`.",
    "",
    "## Sources used",
    kable(sources_used, format = "markdown")
  )

  lines <- c(
    lines, "",
    "## FBref access",
    "fbref.com itself returns HTTP 403 (Cloudflare Managed Challenge) on the very",
    "first request, independent of user agent -- confirmed 2026-09-20. Every FBref",
    "page this project reads is instead fetched from a specific Internet Archive",
    "Wayback Machine snapshot (`cache_fetch_wayback()`, `R/01_sources.R`); the",
    "manifest records the original fbref.com URL, not the archive.org one -- the",
    "Archive is transport, not the source. See `THIRD_PARTY_NOTICES.md` for the",
    "full evidence trail (worldfootballR archived, TLS impersonation tried and",
    "failed) and Sports Reference's bot policy.",
    "",
    "## Sources considered and not used",
    "- **worldfootballR**: the R package that used to wrap FBref is archived",
    "  (2025-09-18, read-only) and its pre-scraped event data",
    "  (`worldfootballR_data`) only covered 2018 onward regardless -- outside",
    "  Shearer's 1992-2006 career. Superseded by direct Wayback access above.",
    "- **dkjorling/FbrefAPI (fbrapi.com)**: service unreachable (connection times out on",
    "  every route), unmaintained, and would still inherit FBref's Cloudflare block.",
    "- **`reticulate` + `soccerdata` (Python)**: its FBref reader",
    "  (`BaseSeleniumReader`) drives real headless Chrome, not a requests-based",
    "  fetch -- porting it would put Python and Chrome in `renv`, against the",
    "  project's pure-R scope, for a reader that still doesn't expose goal events.",
    "- **Understat**: xG/shots coverage starts 2014/15, outside the era.",
    "- **football-data.org API**: returns 403 without a paid key."
  )

  writeLines(lines, path)
  path
}

#' Known limitations, each tied to a cfg value so the numbers referenced here
#' can't silently drift from what the rest of the pipeline actually uses.
#'
#' @param cfg Parsed config list (from `load_config()` / config/config.yaml).
#' @param path Output file path.
#' @return The `path` written to, invisibly usable for chaining into `_targets.R`.
#' @export
write_limitations_report <- function(cfg, path) {
  lines <- c(
    "# Limitations",
    "",
    "Generated by `R/12_reports.R`.",
    "",
    "- **Single-opponent sample sizes are small**: the rival explorer's \"scored in x/n",
    "  meetings\" rate is reported with two intervals rather than a flat percentage -- a",
    "  Wilson score interval and a Beta-Binomial credible interval (Jeffreys prior,",
    "  Beta(0.5, 0.5)). They agree closely at moderate n and diverge where x is 0 or n,",
    "  which is the point of showing both rather than picking one.",
    "- **No spatial analysis of the 260 goals**: `location_level = \"none\"`. The only open",
    "  event data with coordinates in Shearer's career (StatsBomb/Hudl, Arsenal's 2003/04",
    "  matches) contains exactly 2 Shearer shots, 0 goals -- shown as evidence of the limit,",
    "  not as a shot map.",
    glue("- **Goals/90 coverage is partial across comparators**: FBref supplies real",
         " per-season minutes (goals/90) only for the players pinned in",
         " `sources.fbref.comparator_player_ids` ({paste(names(cfg$sources$fbref$comparator_player_ids), collapse = ', ')})."),
    "  Every other player on the all-time 100+ list keeps `goals_per_90`/",
    "  `adjusted_goals_per_90` as `NA` -- a declared coverage gap, not a guess --",
    "  while `goals_per_appearance` (Wikipedia-sourced) stays populated for all of them.",
    "- **goals_per_90 requires matching FBref/Wikipedia career spans**: `historical_table()`",
    "  (`R/10_analyse_comparators.R`) sets `goals_per_90`/`adjusted_goals_per_90`/",
    "  `minutes_per_goal_or_assist` to `NA` whenever a comparator's cached FBref page",
    "  covers fewer career goals than Wikipedia's all-time total -- dividing a full-career",
    "  numerator by partial-career minutes would silently inflate the rate (caught for",
    "  Harry Kane's 2019-20-truncated snapshot before this guard existed). Named mismatches",
    "  are listed in `docs/validation.md`.",
    "- **Clutch-context coverage is per-player, not uniform**: the equaliser/go-ahead",
    "  breakdown for the 9 historical comparators (Phase 7, `comparator_context_breakdown_for()`)",
    "  depends on that player's own ~1,400 match reports having a Wayback capture. Reports",
    "  the Archive never captured are excluded from that player's denominator, not imputed --",
    "  see `docs/coverage.md` for the full list, named by match.",
    "- **Era adjustment is coarse by construction**: Wikipedia's all-time list gives each",
    "  player's career span as first/last *calendar year of appearance*, not a season list --",
    "  a player active `2012||2023` is assumed to have played every season in between, which",
    "  can misdate the span by up to one season at either edge. The adjustment also averages",
    "  the scoring environment evenly across that whole span; a player whose appearances",
    "  cluster in a few seasons of a long career gets an environment estimate weighted by",
    "  seasons present, not by appearances actually made in each. (FBref's own per-season",
    "  tables would let this be verified season-by-season instead, for the players it",
    "  covers -- not yet wired into `career_era_index()`, which still runs off Wikipedia's span.)",
    "- **1992-93 has no full-league scoring-environment measurement**: football-data.co.uk",
    "  starts at 1993-94 and no other source here covers every match in the league that",
    "  season, so the era index for any career including 1992-93 is built from one fewer",
    "  season than it should be -- one season out of Shearer's fourteen."
  )

  writeLines(lines, path)
  path
}
